<?php
/**
 * Created by PhpStorm.
 * User: PC
 * Date: 2017/6/14
 * Time: 11:39
 */

namespace backend\controllers;

use common\models\ActivityBargain;
use common\models\ActivityCrowdFunding;
use common\models\CrowdFundingGear;
use yii;

class ActivityCrowdFundingController extends PublicBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionActivityList(){
        $company_id = yii::$app->request->post('company_id', 0);
        $page = yii::$app->request->post('page', 1);
        $size = yii::$app->request->post('size', 10);

        $return_data = ActivityCrowdFunding::activityList($company_id, $page, $size);
        $this->_successData($return_data);
    }

    /**
     * 后台添加众筹活动  第一步
     */
    public function actionAddActivitySetupOne(){
        $company_id  = yii::$app->request->post('company_id', 0);
        $activity_id = yii::$app->request->post('activity_id', 0);
        $title       = yii::$app->request->post('title', '');
        $category    = yii::$app->request->post('category', '');
        $tag         = yii::$app->request->post('tag', '');
        $abstract    = yii::$app->request->post('abstract', '');
        $cover_img   = yii::$app->request->post('cover_img', '');
        if(!$company_id || !$title || !$cover_img) $this->_errorData('1001', '参数错误');

        $ret = ActivityCrowdFunding::addActivitySetupOne($company_id, $activity_id, $title, $category, $tag, $abstract, $cover_img);
        if($ret) $this->_successData($ret);
        $this->_errorData('1000', '活动创建失败');
    }

    /**
     * 后台添加众筹活动  第二步
     */
    public function actionAddActivitySetupTwo(){
        $company_id  = yii::$app->request->post('company_id', 0);
        $activity_id = yii::$app->request->post('activity_id', 0);
        $introduce   = yii::$app->request->post('introduce', '');
        if(!$activity_id) $this->_errorData('2000', '参数错误');

        $ret = ActivityCrowdFunding::addActivitySetupTwo($activity_id, $introduce);
        if($ret) $this->_successData('操作成功');
        $this->_errorData('2001', '操作失败');
    }

    /**
     * 后台添加众筹活动  第三步
     */
    public function actionAddActivitySetupThree(){
        $company_id  = yii::$app->request->post('company_id', 0);
        $activity_id = yii::$app->request->post('activity_id', 0);
        $gear_id = yii::$app->request->post('gear_id', 0);
        $title   = yii::$app->request->post('title', '');
        $huiwenbi   = yii::$app->request->post('huiwenbi', '');
        $description   = yii::$app->request->post('description', '');
        $img   = yii::$app->request->post('img', '');
        $quota_limit   = yii::$app->request->post('quota_limit', '');
        $quota_num   = yii::$app->request->post('quota_num', '');
        $support_limit   = yii::$app->request->post('support_limit', '');
        $support_num   = yii::$app->request->post('support_num', '');
        $mail_type   = yii::$app->request->post('mail_type', '');
        $package_mail   = yii::$app->request->post('package_mail', '');
        if(!$activity_id || !$title || !$huiwenbi || !$img) $this->_errorData('3000', '参数错误');

        $ret = ActivityCrowdFunding::addActivitySetupThree($activity_id, $gear_id, $title, $huiwenbi, $description, $img, $quota_limit, $quota_num, $support_limit, $support_num, $mail_type, $package_mail);
        if($ret) $this->_successData('操作成功');
        $this->_errorData('3001', '操作失败');
    }

    /**
     * 后台添加众筹活动  第四步
     */
    public function actionAddActivitySetupFour(){
        $company_id  = yii::$app->request->post('company_id', 0);
        $activity_id = yii::$app->request->post('activity_id', 0);
        $day = yii::$app->request->post('day', 0);
        $huiwenbi = yii::$app->request->post('huiwenbi', 0);
        $return_time = yii::$app->request->post('return_time', 0);
        if(!$activity_id) $this->_errorData('4000', '参数错误');

        $ret = ActivityCrowdFunding::addActivitySetupFour($activity_id, $day, $huiwenbi, $return_time);
        $this->_successData($ret);
    }

    /**
     * 后台众筹活动 档位列表
     */
    public function actionActivityGearList(){
        $company_id  = yii::$app->request->post('company_id', 0);
        $activity_id = yii::$app->request->post('activity_id', 0);
        $page = yii::$app->request->post('page', 1);
        $size = yii::$app->request->post('size', 10);

        $list  = CrowdFundingGear::getGearList($activity_id, $page, $size);
        $this->_successData($list);
    }
}