<?php
/**
 * Created by PhpStorm.
 * User: PC
 * Date: 2017/8/19
 * Time: 14:12
 */

namespace backend\controllers;

use yii;
use common\models\Goods;
use common\models\ShopOrder;

class ShopStaticisController extends PublicBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionStat(){
        $company_id = yii::$app->request->post('company_id', 1);

        /* 订单信息统计 */
        //已成交订单 （ 已收货
        $received_order_count = ShopOrder::find()->where(['company_id'=>$company_id, 'is_del'=>0])->andWhere(['>=', 'status', 4])->andWhere(['<>', 'status', '6'])->count();

        //等待发货订单
        $wait_delivery_count  = ShopOrder::find()->where(['company_id'=>$company_id, 'is_del'=>0, 'status'=>2])->count();

        //未确认订单
        $no_confirm_order_count = ShopOrder::find()->where(['company_id'=>$company_id, 'is_del'=>0, 'status'=>1])->count();

        /* 实体商品统计 */
        //商品总数
        $goods_count = Goods::find()->where(['company_id'=>$company_id, 'goods_type'=>1, 'is_shelves'=>1, 'is_recovery'=>0])->count();

        //库存警告商品数
        $stock_warning_goods_count = Goods::find()->where(['company_id'=>$company_id, 'goods_type'=>1, 'is_shelves'=>1, 'is_recovery'=>0])->andWhere("goods_stock_warning > goods_stock")->count();

        /* 虚拟商品统计信息 */
        //商品总数
        $virtual_goods_count = Goods::find()->where(['company_id'=>$company_id, 'goods_type'=>2, 'is_shelves'=>1, 'is_recovery'=>0])->count();

        //库存警告商品数
        $stock_warning_virtual_goods_count = Goods::find()->where(['company_id'=>$company_id, 'goods_type'=>2, 'is_shelves'=>1, 'is_recovery'=>0])->andWhere("goods_stock_warning > goods_stock")->count();

        $return_data = [
            'received_order_count' => $received_order_count,
            'wait_delivery_count' => $wait_delivery_count,
            'no_confirm_order_count' => $no_confirm_order_count,

            'goods_count' => $goods_count,
            'stock_warning_goods_count' => $stock_warning_goods_count,

            'virtual_goods_count' => $virtual_goods_count,
            'stock_warning_virtual_goods_count' => $stock_warning_virtual_goods_count,
        ];
        $this->_successData($return_data);
    }
}