<?php
/**
 * Created by PhpStorm.
 * User: PC
 * Date: 2017/7/3
 * Time: 17:13
 */

namespace backend\controllers;

use common\models\Company;
use common\models\CompanyMessageRecord;
use common\models\Message;
use yii;

class ShopMsgController extends PublicBaseController
{
    protected $not_del_msg_code;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stu
        $this->not_del_msg_code = 0;
    }

    /**
     * 消息列表
     */
    public function actionMsgList(){
        $msg_list = Message::find()
            ->where(['is_del'=>$this->not_del_msg_code])
            ->asArray()
            ->all();
        $msg_list || $msg_list = [];

        $this->_successData($msg_list);
    }

    /**
     * 公司列表  发给分公司的消息是否已读
     */
    public function actionMsgCompanyStatus()
    {
        $msg_id = yii::$app->request->post('msg_id', 0);
        if(!$msg_id) $this->_errorData('2000', '参数错误');

        $list = Company::find()
            ->alias('c')
//            ->select(['c.company_id', 'c.name as company_name', 'IF(cmr.read_time, 1, 0) as is_read', 'cmr.read_time'])
            ->select(['c.company_id', 'c.name as company_name', 'cmr.is_read', 'cmr.read_time'])
            ->leftJoin('vrshop.company_message_record cmr', 'c.company_id = cmr.company_id')
            ->orderBy('cmr.read_time DESC')
            ->asArray()
            ->all();
        $list || $list = [];

        $this->_successData($list);
    }

    /**
     * 添加消息
     */
    public function actionAddMsg(){
        $msg_title     = yii::$app->request->post('msg_title', '');
        $msg_content   = yii::$app->request->post('msg_content', '');
        $msg_type      = yii::$app->request->post('msg_type', 0);   //0 系统消息  1 活动通知
        $to_company_id = yii::$app->request->post('company_id', 0); //0 全部  非零 分公司id，逗号分隔
        if(!$msg_title || !$msg_content) $this->_errorData('1000', '参数错误');

        $insert_msg_ret = yii::$app->db->createCommand()->insert([
            'message_title'   => $msg_title,
            'message_content' => $msg_content,
            'company_id'      => $to_company_id,
            'message_type'    => $msg_type,
            'create_time'     => date('Y-m-d H:i:s', time()),
        ])->execute();

        if($insert_msg_ret) $this->_successData('添加成功');

        $this->_errorData('1001', '添加失败');
    }
}