<?php

use yii\db\Migration;

class m161227_075353_live extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live}}', 'news_id', "bigint(20) default 0 COMMENT '新闻id' ");
    }

    public function down()
    {
        echo "m161227_075353_live cannot be reverted.\n";

        return false;
    }


}
