<?php

use yii\db\Migration;

class m161227_033825_update_news_column extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{news_column}}', 'show_type', "tinyint(4) default '1' COMMENT '栏目所属 1通用 2app 3pc'");
        $this->update('{{news_column}}', ['show_type'=>1]);
    }

    public function down()
    {
        echo "m161227_032530_alter_news_column cannot be reverted.\n";

        return false;
    }
    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
