<?php

use yii\db\Migration;

class m161228_104128_alter_user extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{user}}', 'countries_regions', "varchar(20) default '' COMMENT '国际区号'");
    }

   

    public function down()
    {
        echo "m161228_104128_alter_user cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
