<?php
use yii\db\Schema;
use yii\db\Migration;

class m161227_075528_column_live_admin extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        $this->createTable('{{column_live_admin}}',[
            'id'        => Schema::TYPE_PK,
            'type'      => Schema::TYPE_SMALLINT . "(3) DEFAULT 0 COMMENT '类型，默认0 常规栏目，1本地栏目'",
            'column_id' => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '栏目ID'",
            'admin_id'  => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '管理员ID'",
        ],$tableOptions);
    }

    public function down()
    {
        echo "m161227_075528_column_live_admin cannot be reverted.\n";

        return false;
    }


}
