<?php

use yii\db\Migration;

class m161229_054635_jingcai_answer_sort extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{quiz_rule}}', 'sort_num', "int(7) NOT NULL default 0 COMMENT '排序'");
    }

    public function down()
    {
        echo "m161229_054635_jingcai_answer_sort cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
