<?php

use yii\db\Migration;

class m170913_022054_updata_activity_guest_prize extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function up()
    {
        $this->addColumn('vrshop.activity_lottery_guests_prize', "goods_attr_id", " BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '商品属性ID' AFTER `goods_id`");
    }

    public function safeDown()
    {
        echo "m170913_022054_updata_activity_guest_prize cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m170913_022054_updata_activity_guest_prize cannot be reverted.\n";

        return false;
    }
    */
}
