<?php

use yii\db\Migration;

class m170719_071320_news_praise_add_count extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{news_praise}}', 'live_count', " int(11) default 0 COMMENT '直播（视频、录播 的快直播类型） 点赞数量'");

    }

    public function down()
    {
        echo "m170719_071320_news_praise_add_count cannot be reverted.\n";

        return false;
    }


}
