<?php

use yii\db\Migration;

class m170822_062844_update_shop_order extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->db = yii::$app->vrshop;
    }

    public function up()
    {
        $this->addColumn('shop_order', 'pay_type', "TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付方式 0：汇闻币 1：汇闻币 + 支付宝 2：汇闻币 + 微信 3：微信 4：支付宝' AFTER `order_type`");
    }

    public function down()
    {
        echo "m170822_062844_update_shop_order cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
