<?php

use yii\db\Migration;

class m170313_061642_news_add extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{news}}', 'vote_id', "bigint(20) default 0 COMMENT '投票id' ");
    }

    public function down()
    {
        echo "m170313_061642_news_add cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
