<?php

use yii\db\Migration;

class m170220_074336_change_task_comment extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->update('{{task}}', ['max_cnt'=>10],['id'=>4]);
    }

    public function down()
    {
        echo "m170220_074336_change_task_comment cannot be reverted.\n";

        return false;
    }

    
}
