<?php

use yii\db\Migration;

class m170914_063051_update_activity_guest_prize extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function safeUp()
    {
        $this->addColumn('vrshop.activity_lottery_guests_prize', "num", "SMALLINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '奖品数量' AFTER `info`");
    }

    public function safeDown()
    {
        echo "m170914_063051_update_activity_guest_prize cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m170914_063051_update_activity_guest_prize cannot be reverted.\n";

        return false;
    }
    */
}
