<?php

use yii\db\Migration;

class m170914_075525_updata_goods extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function safeUp()
    {
        $this->alterColumn('{{goods}}', 'goods_name', "VARCHAR(200) NOT NULL COMMENT '商品名称'");
    }

    public function safeDown()
    {
        echo "m170914_075525_updata_goods cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m170914_075525_updata_goods cannot be reverted.\n";

        return false;
    }
    */
}
