<?php

use yii\db\Migration;

class m170713_083227_cities extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrnews1;
    }

    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB COMMENT='行政区域地州市信息表'";
        }
        $this->createTable('{{cities}}',[
            "id" =>$this->primaryKey(),
            "cityid" => $this->string(20)->notNull()->defaultValue(0)->comment('城市ID'),
            "city" => $this->string(50)->notNull()->defaultValue(0)->comment('城市名称'),
            "provinceid" => $this->string(20)->notNull()->defaultValue(0)->comment('省份ID'),
        ],$tableOptions);
    }

    public function down()
    {
        echo "m170713_083227_cities cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
