<?php

use yii\db\Migration;

class m170725_091652_add_live_channel_type extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live_channel}}', 'type', " tinyint(4) default 0 COMMENT '频道使用类型，0后台使用，1采集端使用（快直播）'");

    }

    public function down()
    {
        echo "m170725_091652_add_live_channel_type cannot be reverted.\n";

        return false;
    }

}
