<?php

use yii\db\Migration;

class m170314_074324_up_vote_option extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{vote_option}}', 'number', "tinyint(4) default 0 COMMENT '编号' ");
    }

    public function down()
    {
        echo "m170314_074324_up_vote_option cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
