<?php

use yii\db\Migration;

class m170704_033426_update_news_column extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{news_column}}', 'ename', "varchar(50) default NULL COMMENT '栏目域名'");
    }

    public function down()
    {
        echo "m170704_033426_update_news_column cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
