<?php

use yii\db\Migration;

class m170111_093714_task_insertone extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->insert('{{task}}',[
            'task_name' => '邀请朋友',
            'amount' => 100,
        ]);
    }

    public function down()
    {
        echo "m170111_093714_task_insertone cannot be reverted.\n";

        return false;
    }

}
