<?php

use yii\db\Migration;

class m170517_090007_news_praise_update extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{news_praise}}', 'news_type', "tinyint(3) default 0 COMMENT '新闻类型 0 直播新闻 1 普通新闻' ");
    }

    public function down()
    {
        echo "m170517_090007_news_praise_update cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
