<?php

use yii\db\Migration;

class m170221_082642_insert_menu_resources extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vradmin1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	public function up()
	{
		    	$this->insert('{{sys_menu}}',[
		    			'menu_id'=>'311',
		    			'parentid' => '0',
		    			'type' => '0',
		    			'status'=>'1',
		    			'name'=>'资料库管理',
		    			'listorder'=>'0'
		    	]);
		    	$this->insert('{{sys_menu}}',[
		    			'menu_id'=>'312',
		    			'parentid' => '311',
		    			'app'=>'Admin',
		    			'model'=>'Resources',
		    			'action'=>'resource_library',
		    			'type' => '0',
		    			'status'=>'1',
		    			'name'=>'资源池',
		    			'listorder'=>'0'
		    	]);
	}

    public function down()
    {
        echo "m170221_082642_insert_menu_resources cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
