<?php

use yii\db\Migration;

class m170623_063804_isnert_area_yanbian extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->insert('{{area}}',[
    			'name' => '延边',
    			'initial' => 'Y',
    			'initial_group' => '5',
    			'pinyin' => 'yanbian',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    }

    public function down()
    {
        echo "m170623_063804_isnert_area_yanbian cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
