<?php

use yii\db\Migration;

class m170706_075209_live_status_category_add extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->alterColumn('{{live}}', 'status', " tinyint(4) default 1 COMMENT '直播状态 1 正常 0 删除 2 已结束 3未开始 4直播中 5直播回顾'");
        $this->alterColumn('{{live}}', 'category', " tinyint(4) default 1 COMMENT '直播类型：0：表示未设置直播类型,请选择;1视频直播;2VR直播;3图文直播;4视频加图文直播;5VR加图文直播;6录播'");
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
