<?php

use yii\db\Migration;

class m170512_054526_resource_libiary_add_column_operation_id extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->addColumn('{{resource_library}}', 'operation_id', "bigint(20) DEFAULT NULL COMMENT '后台操作用户id' ");
    }

    public function down()
    {
        echo "m170512_054526_resource_libiary_add_column_operation_id cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
