<?php

use yii\db\Migration;

class m170720_072102_alter_admin_user extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{admin_user}}', 'company_id', "bigint(20) default '0' COMMENT '管理的公司ID'");
    }

    public function down()
    {
        echo "m170720_072102_alter_admin_user cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
