<?php

use yii\db\Migration;

class m170112_024957_user_add_invite_status extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{user}}', 'invite_status', "tinyint(4) default '0' COMMENT '是否通过邀请状态，0否，1是,2是且已激活'");
    }

    public function down()
    {
        echo "m170112_024957_user_add_invite_status cannot be reverted.\n";

        return false;
    }

}
