<?php

use yii\db\Migration;

class m170616_022336_alert_live_add_column_true_play_count extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrlive;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->addColumn('{{live}}', 'true_play_count', "int(11) default '0' COMMENT '真实点击次数'");
    }

    public function down()
    {
        echo "m170616_022336_alert_live_add_column_true_play_count cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
