<?php

use yii\db\Migration;

class m170803_022212_live_channel_add_max extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->alterColumn('{{live_channel}}', 'txy_channel_id', " varchar(50) COMMENT '腾讯云返回的id 或 直播码'");
    }

    public function down()
    {
        echo "m170803_022212_live_channel_add_max cannot be reverted.\n";

        return false;
    }

    
}
