<?php

use yii\db\Migration;

class m170411_060718_vote_option_update extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->alterColumn('{{vote_option}}', 'number', " int(8) default 0");
    }

    public function down()
    {
        echo "m170411_060718_vote_option_update cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
