<?php

use yii\db\Migration;

class m170804_091407_live_push_time_main_edit extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->alterColumn('{{live}}', 'push_time', " int(11) default 0 COMMENT '获取直播中 更新断流时间'");
    }

    public function down()
    {
        echo "m170804_091407_live_push_time_main_edit cannot be reverted.\n";

        return false;
    }

}
