<?php

use yii\db\Migration;

class m170704_034043_update_news_column_ename extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->update('news_column', ['ename' => 'wrest'], ['name' => '跤坛']);
        $this->update('news_column', ['ename' => 'law'], ['name' => '说法']);
        $this->update('news_column', ['ename' => 'commonweal'], ['name' => '公益']);
        $this->update('news_column', ['ename' => 'company'], ['name' => '公司']);
        $this->update('news_column', ['ename' => 'education'], ['name' => '教育']);
        $this->update('news_column', ['ename' => 'life'], ['name' => '生活']);
        $this->update('news_column', ['ename' => 'video'], ['name' => '视频']);
        $this->update('news_column', ['ename' => 'city-manage'], ['name' => '城市管理']);
        $this->update('news_column', ['ename' => 'e-zine'], ['name' => '电子杂志']);
    }

    public function down()
    {
        echo "m170704_034043_update_news_column_ename cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
