<?php

use yii\db\Migration;

class m170628_083840_add_live_isfast extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live}}', 'is_fast', "tinyint(4) default 0 COMMENT '是否快直播，0否，1是'");
    }

    public function down()
    {
        echo "m170628_083840_add_live_isfast cannot be reverted.\n";

        return false;
    }

}
