<?php

use yii\db\Migration;

class m170317_051728_alter_user_nickname extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->alterColumn('{{user}}', 'nickname', " varchar(500) default NULL ");
    }

    public function down()
    {
        echo "m170317_051728_alter_user_nickname cannot be reverted.\n";

        return false;
    }

 
}
