<?php

use yii\db\Migration;

class m170724_093702_add_live_pushtime extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live}}', 'push_time', " int(11) default 0 COMMENT '获取直播中的 直播状态 的更新时间'");

    }

    public function down()
    {
        echo "m170724_093702_add_live_pushtime cannot be reverted.\n";

        return false;
    }


}
