<?php

use yii\db\Migration;

class m170425_025321_resource_add_column_is_water extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->addColumn('{{resource_library}}', 'is_water', "tinyint(4) default '0' COMMENT '图片是否添加水印'");
    }

    public function down()
    {
        echo "m170425_025321_resource_add_column_is_water cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
