<?php

use yii\db\Migration;

class m170208_055027_sys_menu extends Migration
{
	
	public function init()
	{
		$this->db = Yii::$app->vradmin1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	public function up()
	{
		    	$this->alterColumn('{{sys_menu}}', 'app',"char(50) NOT NULL COMMENT '应用名称app' ");
	}
	

    public function down()
    {
        echo "m170208_055027_sys_menu cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
