<?php

use yii\db\Migration;

class m170703_075715_alter_panel_manage_sort_number extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->alterColumn('{{live_panel_manage}}', 'sort_number', " int(11) default 0 COMMENT '图文消息的排序序号'");
    }

    public function down()
    {
        echo "m170703_075715_alter_panel_manage_sort_number cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
