<?php

use yii\db\Migration;

class m170713_070308_insert_area_zhongshan extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->insert('{{area}}',[
    			'name' => '中山',
    			'initial' => 'Z',
    			'initial_group' => '5',
    			'pinyin' => 'zhongshan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);

    }

    public function down()
    {
        echo "m170713_070308_insert_area_zhongshan cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
