<?php

use yii\db\Migration;

class m170417_074508_insert_area extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->insert('{{area}}',[
    			'name' => '延吉',
    			'initial' => 'Y',
    			'initial_group' => '5',
    			'pinyin' => 'yanji',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '重庆',
    			'initial' => 'C',
    			'initial_group' => '1',
    			'pinyin' => 'chongqing',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '温州',
    			'initial' => 'W',
    			'initial_group' => '5',
    			'pinyin' => 'wenzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    }

    public function down()
    {
        echo "m170417_074508_insert_area cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
