<?php

use yii\db\Migration;

class m170907_074650_updata_task extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vruser1;
    }

    public function up()
    {
        $this->update('task', ['amount'=>10, 'max_cnt'=>10], ['id'=>1]);
        $this->update('task', ['amount'=>5, 'max_cnt'=>5], ['id'=>2]);
        $this->update('task', ['amount'=>5, 'max_cnt'=>5], ['id'=>3]);
        $this->update('task', ['amount'=>5, 'max_cnt'=>5], ['id'=>4]);
        $this->update('task', ['amount'=>5, 'max_cnt'=>5], ['id'=>5]);
        $this->update('task', ['amount'=>100, 'max_cnt'=>300], ['id'=>6]);
    }

    public function down()
    {
        echo "m170907_074650_updata_task cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
