<?php

use yii\db\Migration;

class m170518_021748_vote_cheat extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrnews1;
    }

    public function up()
    {
        $this->createTable('vote_cheat',
            array(
                'id' => $this->primaryKey(),
                'user_id' => $this->bigInteger(20)->notNull()->defaultValue(0)->comment('投票人的ID'),
                'to_user_id' => $this->bigInteger(20)->notNull()->defaultValue(0)->comment('被投票人的ID'),
                'create_time' => $this->integer(10)->notNull()->defaultValue(0)->comment('投票时间'),
            ));
    }

    public function down()
    {
        echo "m170518_021748_vote_cheat cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
