<?php
use yii\db\Schema;
use yii\db\Migration;

class m170117_064012_invite_download extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        $this->createTable('{{invite_download}}',[
            'id'               => Schema::TYPE_PK,
            'user_id'          => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '邀请人ID'",
            'type'             => Schema::TYPE_SMALLINT . "(3) DEFAULT 0 COMMENT '类型 0 ios,1 android'",
            'create_time'      => Schema::TYPE_DATETIME." DEFAULT NULL COMMENT '添加时间'",
        ],$tableOptions);
    }

    public function down()
    {
        echo "m170117_064012_invite_download cannot be reverted.\n";

        return false;
    }


}
