<?php

use yii\db\Migration;

class m170822_015347_update_shop_goods extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function up()
    {
        $this->addColumn('{{goods}}', 'pay_type', "TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付方式  0 ：汇闻币  1：汇闻币 + 第三方支付  2：第三方支付' AFTER `art_no`");
        $this->addColumn('{{goods}}', 'video_url', "VARCHAR(200) NOT NULL DEFAULT '' COMMENT '商品视频介绍地址' AFTER `art_no` ");
        $this->addColumn('{{goods}}', 'rmb_price', "DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0' COMMENT '商品人民币价格' AFTER `huiwenbi` ");
    }

    public function down()
    {
        echo "m170822_015347_update_shop_goods cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
