<?php

use yii\db\Migration;

class m170327_072916_update_sys_menu_admin extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{sys_menu_admin}}', 'company_id', "bigint(20) default 0 COMMENT '管理的公司ID， 只有menu_id 316 314 才有这个值' ");
    }

    public function down()
    {
        echo "m170327_072916_update_sys_menu_admin cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
