<?php

use yii\db\Migration;

class m170913_022015_updata_activity extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function up()
    {
        $this->addColumn('activity_lottery','stock_return', 'TINYINT UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'是否退还了商品库存 1 是  0 否\' AFTER `status`');
    }

    public function safeDown()
    {
        echo "m170913_022015_updata_activity cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m170913_022015_updata_activity cannot be reverted.\n";

        return false;
    }
    */
}
