<?php

use yii\db\Migration;

class m170714_062601_live_rever_img_url extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live}}', 'rever_img_url', " varchar(200) default null COMMENT '回放视频 缩略图'");

    }

    public function down()
    {
        echo "m170714_062601_live_rever_img_url cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
