<?php

use yii\db\Migration;

class m170828_024331_invite_reg extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB COMMENT='邀请注册表'";
        }
        $this->createTable('{{invite_reg}}',[
            "id"             =>$this->primaryKey(),
            "images"         => "varchar(255) DEFAULT NULL COMMENT '页面图片' ",
            "share_title"    => "varchar(255) DEFAULT NULL COMMENT '分享标题' ",
            "share_abstract" => "varchar(255) DEFAULT NULL COMMENT '分享摘要' ",
            "share_img"      => "varchar(255) DEFAULT NULL COMMENT '分享图片' ",
            "create_time"    => "int(10) NOT NULL DEFAULT 0 COMMENT '创建时间' ",
            "create_id"      => "int(11) DEFAULT 0 COMMENT '创建人ID' ",
        ],$tableOptions);
    }

    public function down()
    {
        echo "m170828_024331_invite_reg cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
