<?php

use yii\db\Migration;

class m170510_023655_insert_area_47citys extends Migration
{
	
	public function init()
	{
		$this->db = Yii::$app->vrnews1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->insert('{{area}}',[
    			'name' => '佛山',
    			'initial' => 'F',
    			'initial_group' => '2',
    			'pinyin' => 'foshan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '潮州',
    			'initial' => 'C',
    			'initial_group' => '1',
    			'pinyin' => 'chaozhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '东莞',
    			'initial' => 'D',
    			'initial_group' => '1',
    			'pinyin' => 'dongguan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '湛江',
    			'initial' => 'Z',
    			'initial_group' => '5',
    			'pinyin' => 'zhanjiang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '茂名',
    			'initial' => 'M',
    			'initial_group' => '3',
    			'pinyin' => 'maoming',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '常州',
    			'initial' => 'C',
    			'initial_group' => '1',
    			'pinyin' => 'changzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '贵港',
    			'initial' => 'G',
    			'initial_group' => '2',
    			'pinyin' => 'guigang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '宜春',
    			'initial' => 'Y',
    			'initial_group' => '5',
    			'pinyin' => 'yichun',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '武汉',
    			'initial' => 'W',
    			'initial_group' => '5',
    			'pinyin' => 'wuhan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '黄冈',
    			'initial' => 'H',
    			'initial_group' => '2',
    			'pinyin' => 'huanggang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '兰州',
    			'initial' => 'L',
    			'initial_group' => '3',
    			'pinyin' => 'lanzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '福州',
    			'initial' => 'F',
    			'initial_group' => '2',
    			'pinyin' => 'fuzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '鞍山',
    			'initial' => 'A',
    			'initial_group' => '1',
    			'pinyin' => 'anshan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '梅州',
    			'initial' => 'M',
    			'initial_group' => '3',
    			'pinyin' => 'meizhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '贵阳',
    			'initial' => 'G',
    			'initial_group' => '2',
    			'pinyin' => 'guiyang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '遵义',
    			'initial' => 'Z',
    			'initial_group' => '5',
    			'pinyin' => 'zunyi',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '攀枝花',
    			'initial' => 'P',
    			'initial_group' => '4',
    			'pinyin' => 'panzhihua',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '三亚',
    			'initial' => 'S',
    			'initial_group' => '4',
    			'pinyin' => 'sanya',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '曲靖',
    			'initial' => 'Q',
    			'initial_group' => '4',
    			'pinyin' => 'qujing',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '昆明',
    			'initial' => 'K',
    			'initial_group' => '3',
    			'pinyin' => 'kunming',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '清远',
    			'initial' => 'Q',
    			'initial_group' => '4',
    			'pinyin' => 'qingyuan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '珠海',
    			'initial' => 'Z',
    			'initial_group' => '5',
    			'pinyin' => 'zhuhai',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '大连',
    			'initial' => 'D',
    			'initial_group' => '1',
    			'pinyin' => 'dalian',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '佛山',
    			'initial' => 'F',
    			'initial_group' => '2',
    			'pinyin' => 'foshan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '银川',
    			'initial' => 'Y',
    			'initial_group' => '5',
    			'pinyin' => 'yinchuan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '张掖',
    			'initial' => 'Z',
    			'initial_group' => '5',
    			'pinyin' => 'zhangye',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '来宾',
    			'initial' => 'L',
    			'initial_group' => '3',
    			'pinyin' => 'laibin',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '柳州',
    			'initial' => 'L',
    			'initial_group' => '3',
    			'pinyin' => 'liuzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '汉中',
    			'initial' => 'H',
    			'initial_group' => '2',
    			'pinyin' => 'hanzhong',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '鄂州',
    			'initial' => 'E',
    			'initial_group' => '1',
    			'pinyin' => 'ezhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '湖州',
    			'initial' => 'H',
    			'initial_group' => '2',
    			'pinyin' => 'huzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '赣州',
    			'initial' => 'G',
    			'initial_group' => '2',
    			'pinyin' => 'ganzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '沈阳',
    			'initial' => 'S',
    			'initial_group' => '4',
    			'pinyin' => 'shenyang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '南宁',
    			'initial' => 'N',
    			'initial_group' => '3',
    			'pinyin' => 'nanning',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '泉州',
    			'initial' => 'Q',
    			'initial_group' => '4',
    			'pinyin' => 'quanzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '天水',
    			'initial' => 'T',
    			'initial_group' => '4',
    			'pinyin' => 'tianshui',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '黔南州',
    			'initial' => 'Q',
    			'initial_group' => '4',
    			'pinyin' => 'qiannanzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '黔西南州',
    			'initial' => 'Q',
    			'initial_group' => '4',
    			'pinyin' => 'qianxinanzhou',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '六盘水',
    			'initial' => 'L',
    			'initial_group' => '3',
    			'pinyin' => 'liupanshui',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '玉溪',
    			'initial' => 'Y',
    			'initial_group' => '5',
    			'pinyin' => 'yuxi',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '衡阳',
    			'initial' => 'H',
    			'initial_group' => '2',
    			'pinyin' => 'hengyang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '襄樊',
    			'initial' => 'X',
    			'initial_group' => '5',
    			'pinyin' => 'xiangfan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '酒泉',
    			'initial' => 'J',
    			'initial_group' => '2',
    			'pinyin' => 'jiuquan',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '桂林',
    			'initial' => 'F',
    			'initial_group' => '2',
    			'pinyin' => 'guilin',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '安康',
    			'initial' => 'A',
    			'initial_group' => '1',
    			'pinyin' => 'ankang',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    	$this->insert('{{area}}',[
    			'name' => '上海',
    			'initial' => 'S',
    			'initial_group' => '4',
    			'pinyin' => 'shanghai',
    			'establish_status' => '0',
    			'disable_status' => '1',
    			'live_status' => '0'
    	]);
    }

    public function down()
    {
        echo "m170510_023655_insert_area_47citys cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
