<?php

use yii\db\Migration;

class m170616_062826_insert_sys_menu extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vradmin1;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->insert('{{sys_menu}}',[
    			'parentid' => '294',
    			'app' => 'Admin',
    			'model' => 'Live',
    			'action' => 'show_count',
    			'data' => '',
    			'type' => '1',
    			'status' => '1',
    			'name' => '查看真实浏览数',
    			'icon' => '',
    			'remark' => '',
    			'listorder' => '0',
    	]);
    }

    public function down()
    {
        echo "m170616_062826_insert_sys_menu cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
