<?php

use yii\db\Migration;

class m170913_021823_live_reviewed_add extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{live}}', 'reviewed_status', " tinyint(4) default 0 COMMENT '审核状态 0审核通过，1待审核，2未通过'");
        $this->addColumn('{{live}}', 'amendments', " varchar(500) default NULL COMMENT '修改意见'");

    }


}
