<?php
use yii\db\Schema;
use yii\db\Migration;

class m170112_063125_invite_create extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vruser1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        $this->createTable('{{invite}}',[
            'id'               => Schema::TYPE_PK,
            'user_id'          => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '邀请人ID'",
            'invite_user_id'   => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '被邀请人ID'",
            'invite_user_name' => "varchar(30) DEFAULT '' COMMENT '被邀请人昵称'",
            'invite_type'      => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '邀请渠道 0朋友圈、1微信好友、2手机QQ、3QQ空间、4新浪微博
'",
            'amount'           => Schema::TYPE_INTEGER . "(11) DEFAULT 0 COMMENT '获得积分'",
            'create_time'      => Schema::TYPE_DATETIME." DEFAULT NULL COMMENT '添加时间'",
            'is_login'         => Schema::TYPE_BIGINT . "(20) DEFAULT 0 COMMENT '是否激活（是否登陆过）'",
            'login_time'       => Schema::TYPE_DATETIME." DEFAULT NULL COMMENT '激活时间'",
        ],$tableOptions);
    }

    public function down()
    {
        echo "m170112_063125_invite_create cannot be reverted.\n";

        return false;
    }


}
