<?php

use yii\db\Migration;

class m170822_024705_update_goods_attr_val extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->db = yii::$app->vrshop;
    }

    public function up()
    {
        $this->addColumn('goods_attribute_values', 'pay_type', "TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付方式  0 ：汇闻币  1：汇闻币 + 第三方支付  2：第三方支付' AFTER `values_content`");
        $this->addColumn('goods_attribute_values', 'rmb_price', "DECIMAL(8,2) UNSIGNED  NOT NULL DEFAULT '0' COMMENT '属性人民币价格' AFTER `price`");
    }

    public function down()
    {
        echo "m170822_024705_update_goods_attr_val cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
