<?php

use yii\db\Migration;

class m170913_023930_admin_user_jiguang extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{admin_user}}', 'registration_id', " varchar(30) default NULL COMMENT '推送注册ID'");

    }
}
