<?php

use yii\db\Migration;

class m170612_065454_alert_live_add_column_view_ranage extends Migration
{
	public function init()
	{
		$this->db = Yii::$app->vrlive;
		parent::init(); // TODO: Change the autogenerated stub
	}
	
    public function up()
    {
    	$this->addColumn('{{live}}', 'view_ranage', "varchar(200) default NULL COMMENT '自定义访问直播对应状态时的访问增加量'");
    }

    public function down()
    {
        echo "m170612_065454_alert_live_add_column_view_ranage cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
