<?php

use yii\db\Migration;

class m170815_030401_alter_live_panel_user_manage extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{live_panel_user_manage}}', 'create_timestamp', "bigint(15) DEFAULT NULL COMMENT '发送消息时间戳'");
    }

    public function down()
    {
        echo "m170815_030401_alter_live_panel_user_manage cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
