<?php

use yii\db\Migration;

class m170601_063417_user_area_push extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yii::$app->vruser1;
    }

    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB COMMENT='投票'";
        }
        $this->createTable('{{user_area_push}}',[
            "id" =>$this->primaryKey(),
            "user_id" => $this->bigInteger(20)->notNull()->defaultValue(0)->comment('前台用户的ID'),
            "create_time" => $this->dateTime()->defaultValue(null)->comment('录入时间'),
            "update_time" => $this->dateTime()->defaultValue(null)->comment('更新时间'),
            "area" => $this->string(50)->notNull()->defaultValue('北京')->comment('地区名称'),
        ],$tableOptions);

        $this->createIndex('user_id', 'user_area_push', ['user_id']);
    }

    public function down()
    {
        echo "m170601_063417_user_area_push cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
