<?php

use yii\db\Migration;

class m170314_091838_up_vote extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $this->addColumn('{{vote}}', 'status', "tinyint(4) default 1 COMMENT '状态， 1显示  0不显示' ");
    }

    public function down()
    {
        echo "m170314_091838_up_vote cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
