<?php

use yii\db\Migration;
use common\models\LiveTagsRelation;
use common\models\Live;
use common\models\News;

class m171129_020944_add_tag_and_news_for_3_forgot_live extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
       
        //所有需要处理的快直播
        $ids =['201715136596208941',
               '201715136538251659',
               '201715134090777283'];
        //$ids = ['201715136699449480', '201715136701931456'];
        //判断live_id是否有效且是否已经生成了对应的news，如果有效且没有对应的news，则生成
        $lives = Live::find()->where(['in', 'live_id', $ids])->all();
        foreach ($lives as $live) {
        
            $checkExist = News::find()->where(['=', 'live_id', $live->live_id])->one();
            if (!$checkExist) {
                // 快直播创建成果后，创建管理关联新闻，状态为待审核
                $news_data = new News();
                //'news_id'      => $news_id_add,
                $news_data['title'] = $live->name;
                $news_data['cover_image'] = $live->image_url;
                $news_data['app_pub'] = 1;
                $news_data['weight'] = 70;
                $news_data['type'] = 15;//新增新闻类型，17.集入口 15.普通快直播
                $news_data['create_time'] = date('Y-m-d H:i:s', time());
                $news_data['refresh_time'] = time();
                $news_data['live_id'] = $live->live_id;
                $news_data['status'] = 0;//   新闻状态，0 已发布，1草稿，2定时发布,3待审核
                // 默认导入北京频道
                $news_data['area_id'] = 1;
                $insert_news = $news_data->save();
                //快直播关联新闻,创建成果后更新直播关联新闻id;
                if ($insert_news) {
                    $live->news_id = $news_data->news_id;
                    $live->update();
                }
            
            }
        }
        // 三条直播绑定“直播”标签
        foreach ($ids as $id){
            $this->insert('{{live_tags_relation}}', [
                'tag_id'    => '2',
                'live_id'        => $id,
                'create_time' => '2017-12-21 11:11:00',
                'creator'     => '1'
            ]);
        }
        
       
    }

    public function safeDown()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }
    */
}
