<?php

use yii\db\Migration;

class m171106_030950_update_shop_goods extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vrshop;
    }

    public function safeUp()
    {
        $this->addColumn(\common\models\Goods::tableName(), 'sale_type', "TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '售卖类型 // 0:全部 1：商城 2：直播间' AFTER `goods_type`");
        $this->addColumn(\common\models\Goods::tableName(), 'live_sale_status', "TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '直播间售卖审核状态 // 0:未通过 1：已通过' AFTER `is_recovery`");
    }

    public function safeDown()
    {
        echo "m171106_030950_update_shop_goods cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171106_030950_update_shop_goods cannot be reverted.\n";

        return false;
    }
    */
}
