<?php

use yii\db\Migration;

class m171018_024826_add_version_data extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->insert('{{admin_version}}',[
            'type' => '0',
            'version' => '1.0.0',
            'create_time' => '2017-10-18 10:00:00',
        ]);
        $this->insert('{{admin_version}}',[
            'type' => '1',
            'version' => '1.0.0',
            'create_time' => '2017-10-18 10:00:00',
        ]);
    }

    public function safeDown()
    {
        echo "m171018_024826_add_version_data cannot be reverted.\n";

        return false;
    }

}
