<?php

use yii\db\Migration;

class m171017_031150_admin_add_update extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{admin_user}}', 'is_update', "tinyint(4)  NOT NULL DEFAULT 1 COMMENT '是否更新过，0更新过，1未更新'");
    }


}
