<?php

use yii\db\Migration;

class m171011_075620_updata_task extends Migration
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = yii::$app->vruser1;
    }

    public function safeUp()
    {
        $this->update('task', ['amount'=>10, 'max_cnt'=>300], ['id'=>6]);
    }

    public function safeDown()
    {
        echo "m171011_075620_updata_task cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171011_075620_updata_task cannot be reverted.\n";

        return false;
    }
    */
}
