<?php

use yii\db\Migration;

class m171219_070633_alter_admin_user_rcloud_token extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->alterColumn('{{admin_user_rcloud_token}}', 'other_rcloud_token1', "varchar(120) DEFAULT NULL COMMENT 'token1'");
        $this->alterColumn('{{admin_user_rcloud_token}}', 'other_rcloud_token2', "varchar(120) DEFAULT NULL COMMENT 'token2'");
    }

    public function safeDown()
    {
        echo "m171219_070633_alter_admin_user_rcloud_token cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171219_070633_alter_admin_user_rcloud_token cannot be reverted.\n";

        return false;
    }
    */
}
