<?php

use yii\db\Migration;
use common\models\LiveTagsRelation;
use common\models\Live;

class m171129_020944_add_tag_for_old_live extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
       
        //所有需要处理的快直播
        $ids =['201715132160633033',
               '201715132382163018',
               '201715128876766036',
               '201715127230517712',
               '201715128424141612',
               '201715127227644981',
               '20171512381424229',
               '201715123686151256',
               '201715123491038093',
               '201715122818896884',
               '201715122660318271',
               '201715122658497128',
               '201715119580357429',
               '201715115077475704',
               '201715112423554704',
               '201715108004677606',
               '201715106218114718',
               '201715101133085611',
               '201715098395147919',
               '201715097626971487',
               '201715092654911625',
               '201715092443573108',
               '201715082058483982',
               '201715080471908844',
               '201715067224876297',
               '201715065970295886',
               '20171506594771111'];
        //$ids = ['201715136692675386', '201715136692478825'];
        foreach ($ids as $id){
            $this->insert('{{live_tags_relation}}', [
                'tag_id'    => '2',
                'live_id'        => $id,
                'create_time' => '2017-12-21 11:11:00',
                'creator'     => '1'
            ]);
        }
        
       
    }

    public function safeDown()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }
    */
}
