<?php

use yii\db\Schema;
use yii\db\Migration;

class m171018_015510_add_admin_version extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vradmin1;
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB COMMENT='后台 版本'";
        }
        $this->createTable('{{admin_version}}',[
            'id'          => Schema::TYPE_PK,
            'type'        => Schema::TYPE_SMALLINT . "(4) DEFAULT 0 COMMENT '系统类型 0 安卓,1 IOS'",
            'version'     => Schema::TYPE_CHAR . "(30) DEFAULT '' COMMENT 'ios 当前版本号'",
            'create_time' => Schema::TYPE_DATETIME." DEFAULT NULL COMMENT '添加时间'",
        ],$tableOptions);
    }

    public function safeDown()
    {
        echo "m171018_015510_add_admin_version cannot be reverted.\n";

        return false;
    }
    
}
