<?php

use yii\db\Migration;

class m171206_015450_alter_live_weme extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{live_weme}}', 'file_id', "varchar(60) DEFAULT NULL COMMENT '腾讯云文件id'");
    }
    public function safeDown()
    {
        echo "m171206_015450_alter_live_weme cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171206_015450_alter_live_weme cannot be reverted.\n";

        return false;
    }
    */
}
