<?php

use yii\db\Migration;

class m171129_020944_insert_live_tags_gaoguan extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->insert('{{live_tags}}',[
            'tag_name' => '直播',
            'type' => '2',
            'status' => '1',
            'create_time' => '2017-12-14 17:11:00',
            'creator' => '1'
        ]);
    }

    public function safeDown()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }
    */
}
