<?php

use yii\db\Migration;
use common\models\News;
use common\models\Live;

class m171129_020944_insert_news_for_old_live extends Migration
{
    /*public function init()
    {
        $this->db = Yii::$app->vrlive;
        parent::init(); // TODO: Change the autogenerated stub
    }*/

    public function up()
    {
        /*$this->insert('{{live_tags}}',[
            'tag_name' => '直播',
            'type' => '2',
            'status' => '1',
            'create_time' => '2017-12-14 17:11:00',
            'creator' => '1'
        ]);*/
        //所有需要处理的快直播
        $ids =['201715132160633033',
               '201715132382163018',
               '201715128876766036',
               '201715127230517712',
               '201715128424141612',
               '201715127227644981',
               '20171512381424229',
               '201715123686151256',
               '201715123491038093',
               '201715122818896884',
               '201715122660318271',
               '201715122658497128',
               '201715119580357429',
               '201715115077475704',
               '201715112423554704',
               '201715108004677606',
               '201715106218114718',
               '201715101133085611',
               '201715098395147919',
               '201715097626971487',
               '201715092654911625',
               '201715092443573108',
               '201715082058483982',
               '201715080471908844',
               '201715067224876297',
               '201715065970295886',
               '20171506594771111'];
        //$ids = ['201715136692675386', '201715136692478825'];
        $lives = Live::find()->where(['in', 'live_id', $ids])->all();
        foreach ($lives as $live) {
        
            $checkExist = News::find()->where(['=', 'live_id', $live->live_id])->one();
            if (!$checkExist) {
                // 快直播创建成果后，创建管理关联新闻，状态为待审核
                $news_data = new News();
                //'news_id'      => $news_id_add,
                $news_data['title'] = $live->name;
                $news_data['cover_image'] = $live->image_url;
                $news_data['app_pub'] = 1;
                $news_data['weight'] = 70;
                $news_data['type'] = 15;//新增新闻类型，17.集入口 15.普通快直播
                $news_data['create_time'] = date('Y-m-d H:i:s', time());
                $news_data['refresh_time'] = time();
                $news_data['live_id'] = $live->live_id;
                $news_data['status'] = 0;//   新闻状态，0 已发布，1草稿，2定时发布,3待审核
                // 默认导入北京频道
                $news_data['area_id'] = 1;
                $insert_news = $news_data->save();
                //快直播关联新闻,创建成果后更新直播关联新闻id;
                if ($insert_news) {
                    $live->news_id = $news_data->news_id;
                    $live->update();
                }
            
            }
        }
       
    }

    public function safeDown()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171129_020944_insert_live_tags cannot be reverted.\n";

        return false;
    }
    */
}
