<?php

use yii\db\Migration;

class m171122_072811_alter_ad_startup_images extends Migration
{
    public function init()
    {
        $this->db = Yii::$app->vrnews1;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->addColumn('{{ad_startup_images}}', 'link', "varchar(200) DEFAULT NULL COMMENT '第三方链接'");
    }

    public function safeDown()
    {
        echo "m171122_072811_alter_ad_startup_images cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m171122_072811_alter_ad_startup_images cannot be reverted.\n";

        return false;
    }
    */
}
