<?php
namespace frontend\controllers;

use common\models\Tencentyun\ImageV2;
use yii;

class ImageSaveController extends PublicBaseController
{
    protected $request;
    protected $temp_image_path;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        $this->temp_image_path = Yii::$app->basePath.'/web/localFile/temp/';
    }

    public function actionGetImageUrl()
    {
        if(Yii::$app->request->isPost){
            $image_url = $this->request->post('image_url');

            if(!$image_url) $this->_errorData(1005, '参数错误');

            //判断文件后缀
            $image_ext = end(explode('.', $image_url));
            if(!in_array($image_ext, array('jpg', 'png', 'jpeg', 'gif'))) $this->_errorData(1002, '请上传图片文件');

            //获取图片
            $image_file = file_get_contents($image_url);

            //写入服务器目录
            $image_path = $this->temp_image_path.uniqid().time().'.'.$image_ext;
            $img_write_ret = file_put_contents($image_path, $image_file);
            if(!$img_write_ret) $this->_errorData(1003, '文件写入失败');

            //上传到万象有图
            $upload_ret = \Tencentyun\ImageV2::upload($image_path, 'vrlive');

            //不管成不成功都在服务器删除
            unlink($image_path);

            //上传万象优图失败
            if($upload_ret['httpcode'] != 200) $this->_errorData(1004, $upload_ret['message']);

            //上传成功  返回值
            $return_data = array('image_ext'=>$image_ext, 'image_url'=>$upload_ret['data']['downloadUrl']);

            $this->_successData($return_data);
        }

        $this->_errorData(1000, '错误的请求方式');
    }

    public function actionUploadImg(){
        if(yii::$app->request->isPost){
            $image_ext        = $this->params['image_ext'] ? $this->params['image_ext'] : '';
            $base64_image_str = $this->params['base64_img_str'] ? $this->params['base64_img_str'] : '';

            if(!$image_ext || !$base64_image_str) $this->_errorData(1206, '上传图片错误');

            //判断文件后缀
            if(!in_array($image_ext, array('jpg', 'png', 'jpeg', 'gif'))) $this->_errorData(1202, '只能上传图片类型');

            $image_name   = md5(time().uniqid()).'.'.$image_ext;
            $image_path   = Yii::$app->basePath.'/web/localFile/temp/';

            if (!is_dir($image_path)) {
                mkdir($image_path, 0777, true);
            }

            if(file_put_contents($image_path.$image_name, base64_decode($base64_image_str))){
                if(filesize($image_path.$image_name) > 5 * 1024 * 1024){
                    $this->_errorData("5002", "文件过大");
                }

                $uploadRet = ImageV2::upload($image_path.$image_name, 'vrlive');

                //不管成不成功删除本地图片
                unlink($image_path.$image_name);

                if ($uploadRet && $uploadRet['httpcode'] == 200) {
                    $imageUrl = $uploadRet['data']['downloadUrl'];
                    $this->_successData($imageUrl);
                } else {
                    //上传失败，返回错误
                    $this->_errorData("1206", "非常抱歉，上传失败");
                }
            }

            $this->_errorData('1203', '文件写入失败');
        }
        $this->_errorData('1200', '请求方式错误');
    }
}