<?php
/**
 * Created by PhpStorm.
 * User: PC
 * Date: 2017/3/24
 * Time: 13:23
 */

namespace frontend\controllers;

use common\models\Personnel;
use yii\db\Query;
use yii;

class PersonnelController extends PublicBaseController
{
    public $request;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = yii::$app->request;
    }

    public function actionSearch(){
        $name = $this->request->post('name', '');
        $id_card = $this->request->post('id_card', '');

        if(!$name) $this->_errorData('110', '请输入员工姓名');
        if(!$id_card) $this->_errorData('111', '请输入员工身份证号后六位');

        $personnel_list_sql = "SELECT p.*, c.name as company_name, c.introduction, c.phone FROM vrnews1.personnel p LEFT JOIN vrnews1.company c ON p.company_id=c.company_id WHERE CASE WHEN p.id_card THEN SUBSTRING(p.id_card,-6)='$id_card' END AND p.name = '$name'";
        $connection  = Yii::$app->db;
        $model = $connection->createCommand($personnel_list_sql);
        $personnel_list = $model->queryAll();

        $this->_successData($personnel_list);
    }
}